sudo: required
dist: trusty

language: cpp

cache:
  apt: true

addons:
  apt:
    packages:
    - g++
    - libboost-all-dev

compiler:
  - g++

script: mkdir build && cd build && cmake .. && make && ctest --verbose && cd ..
